# Generated by Django 2.1.1 on 2019-10-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='existence',
            field=models.BooleanField(default=True),
        ),
    ]
